spring:
  application:
    name: cineflow
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  thymeleaf:
    cache: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
    validate-on-migrate: true
    clean-disabled: true

server:
  port: 8080

app:
  seed:
    enabled: false
